name: K. M. Naimul Hassan
title: K. M. Naimul Hassan
author: K. M. Naimul Hassan
url: https://naimulhassan.github.io
base: ''

markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: rouge

cadeprefix: "/cade-series"

kramdown:
  input: GFM

liquid:
  error_mode: lax

exclude:
    - bower_components
    - node_modules
    - package.json
    - bower.json
    - drafts

navigation:
    - title: about
      link: /index.html
    - title: research
      link: /research.html
    - title: CV
      link: /content/CV.pdf

plugins:
  - jekyll-redirect-from
  - jekyll-gist