name: K. M. Naimul Hassan
title: K. M. Naimul Hassan
author: K. M. Naimul Hassan
url: https://naimulhassan.github.io
base: ''

markdown: kramdown
kramdown:
    enable_coderay: false
    auto_ids: false
    entity_output: symbolic
highlighter: rouge

exclude:
    - bower_components
    - node_modules
    - package.json
    - bower.json
    - drafts

navigation:
    - title: about
      link: /index
      name: about
    - title: research
      link: /research
    - title: CV
      link: /content/CV.pdf

theme: jekyll-theme-minimal

sass:
  sass_dir: _sass
