name: Dana&euml; Metaxa
author: Dana&euml; Metaxa
url: https://dmetaxak.github.io
base: ''
twitter: '@dmetaxak'

markdown: kramdown
kramdown:
    enable_coderay: false
    auto_ids: false
    entity_output: symbolic
highlighter: pygments

exclude:
    - bower_components
    - node_modules
    - package.json
    - bower.json
    - drafts

navigation:
    - title: research
      link: /research.html
    - title: contact
      link: /contact.html
    - title: CV
      link: /content/CV.pdf